#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _HCN1_reg();
extern void _IC_reg();
extern void _IKsin_reg();
extern void _MyExp2SynBB_reg();
extern void _MyExp2SynNMDABB_reg();
extern void _ar_traub_reg();
extern void _cadad_reg();
extern void _cadyn_reg();
extern void _cagk_reg();
extern void _cal_mh_reg();
extern void _cal_mig_reg();
extern void _can_mig_reg();
extern void _canin_reg();
extern void _cat_mig_reg();
extern void _cat_traub_reg();
extern void _catcb_reg();
extern void _gabab_reg();
extern void _h_BS_reg();
extern void _h_harnett_reg();
extern void _h_kole_reg();
extern void _h_migliore_reg();
extern void _hin_reg();
extern void _ican_sidi_reg();
extern void _kBK_reg();
extern void _kap_BS_reg();
extern void _kapcb_reg();
extern void _kapin_reg();
extern void _kctin_reg();
extern void _kdmc_BS_reg();
extern void _kdr_BS_reg();
extern void _kdrin_reg();
extern void _nafx_reg();
extern void _nap_sidi_reg();
extern void _nax_BS_reg();
extern void _savedist_reg();
extern void _vecstim_reg();

void modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," HCN1.mod");
fprintf(stderr," IC.mod");
fprintf(stderr," IKsin.mod");
fprintf(stderr," MyExp2SynBB.mod");
fprintf(stderr," MyExp2SynNMDABB.mod");
fprintf(stderr," ar_traub.mod");
fprintf(stderr," cadad.mod");
fprintf(stderr," cadyn.mod");
fprintf(stderr," cagk.mod");
fprintf(stderr," cal_mh.mod");
fprintf(stderr," cal_mig.mod");
fprintf(stderr," can_mig.mod");
fprintf(stderr," canin.mod");
fprintf(stderr," cat_mig.mod");
fprintf(stderr," cat_traub.mod");
fprintf(stderr," catcb.mod");
fprintf(stderr," gabab.mod");
fprintf(stderr," h_BS.mod");
fprintf(stderr," h_harnett.mod");
fprintf(stderr," h_kole.mod");
fprintf(stderr," h_migliore.mod");
fprintf(stderr," hin.mod");
fprintf(stderr," ican_sidi.mod");
fprintf(stderr," kBK.mod");
fprintf(stderr," kap_BS.mod");
fprintf(stderr," kapcb.mod");
fprintf(stderr," kapin.mod");
fprintf(stderr," kctin.mod");
fprintf(stderr," kdmc_BS.mod");
fprintf(stderr," kdr_BS.mod");
fprintf(stderr," kdrin.mod");
fprintf(stderr," nafx.mod");
fprintf(stderr," nap_sidi.mod");
fprintf(stderr," nax_BS.mod");
fprintf(stderr," savedist.mod");
fprintf(stderr," vecstim.mod");
fprintf(stderr, "\n");
    }
_HCN1_reg();
_IC_reg();
_IKsin_reg();
_MyExp2SynBB_reg();
_MyExp2SynNMDABB_reg();
_ar_traub_reg();
_cadad_reg();
_cadyn_reg();
_cagk_reg();
_cal_mh_reg();
_cal_mig_reg();
_can_mig_reg();
_canin_reg();
_cat_mig_reg();
_cat_traub_reg();
_catcb_reg();
_gabab_reg();
_h_BS_reg();
_h_harnett_reg();
_h_kole_reg();
_h_migliore_reg();
_hin_reg();
_ican_sidi_reg();
_kBK_reg();
_kap_BS_reg();
_kapcb_reg();
_kapin_reg();
_kctin_reg();
_kdmc_BS_reg();
_kdr_BS_reg();
_kdrin_reg();
_nafx_reg();
_nap_sidi_reg();
_nax_BS_reg();
_savedist_reg();
_vecstim_reg();
}
